-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-22 15:30:22 BRT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_spa_cultura (
    cd_cultura      NUMBER NOT NULL,
    nm_cultura      VARCHAR2(100),
    dt_criado_em    TIMESTAMP NOT NULL,
    dt_alterado_em  TIMESTAMP NOT NULL,
    cd_criado_por   NUMBER,
    cd_alterado_por NUMBER
);

COMMENT ON COLUMN t_spa_cultura.cd_cultura IS
    'adicionando git';

ALTER TABLE t_spa_cultura ADD CONSTRAINT t_spa_cultura_pk PRIMARY KEY ( cd_cultura );

CREATE TABLE t_spa_estado (
    cd_estado       NUMBER NOT NULL,
    nm_estado       VARCHAR2(50),
    dt_criado_em    TIMESTAMP NOT NULL,
    dt_alterado_em  TIMESTAMP NOT NULL,
    cd_criado_por   NUMBER,
    cd_alterado_por NUMBER
);

ALTER TABLE t_spa_estado ADD CONSTRAINT t_spa_estado_pk PRIMARY KEY ( cd_estado );

CREATE TABLE t_spa_permissao (
    cd_permissao    NUMBER NOT NULL,
    nm_permissao    VARCHAR2(50 CHAR) NOT NULL,
    ds_permissao    CLOB,
    dt_criacao      TIMESTAMP DEFAULT current_timestamp,
    dt_alteracao    TIMESTAMP,
    nm_criado_por   VARCHAR2(50 CHAR),
    nm_alterado_por VARCHAR2(50 CHAR)
);

ALTER TABLE t_spa_permissao ADD CONSTRAINT t_spa_permissao_pk PRIMARY KEY ( cd_permissao );

ALTER TABLE t_spa_permissao ADD CONSTRAINT index_1 UNIQUE ( nm_permissao );

CREATE TABLE t_spa_producao (
    cd_producao                    NUMBER NOT NULL,
    cd_cultura                     NUMBER,
    cd_estado                      NUMBER,
    vl_producao_toneladas          FLOAT,
    vl_area_plantada_ha            FLOAT,
    cl_classificacao_produtividade VARCHAR2(50),
    dt_criado_em                   TIMESTAMP NOT NULL,
    dt_alterado_em                 TIMESTAMP NOT NULL,
    cd_criado_por                  NUMBER,
    cd_alterado_por                NUMBER
);

ALTER TABLE t_spa_producao ADD CONSTRAINT t_spa_producao_pk PRIMARY KEY ( cd_producao );

CREATE TABLE t_spa_produtores (
    cd_produtores  NUMBER NOT NULL,
    cd_cultura     NUMBER,
    cd_estado      NUMBER,
    qt_produtores  INTEGER,
    dt_criado_em   TIMESTAMP NOT NULL,
    dt_alterado_em TIMESTAMP NOT NULL,
    cd_criado_por  NUMBER
);

ALTER TABLE t_spa_produtores ADD CONSTRAINT t_spa_produtores_pk PRIMARY KEY ( cd_produtores );

CREATE TABLE t_spa_usuario (
    cd_usuario                  NUMBER NOT NULL,
    nm_usuario                  VARCHAR2(50 CHAR) NOT NULL,
    ds_senha                    BLOB NOT NULL,
    dt_ultimo_login             TIMESTAMP,
    ds_ultima_localizacao_login VARCHAR2(100 CHAR),
    dt_criacao                  TIMESTAMP DEFAULT current_timestamp,
    dt_alteracao                TIMESTAMP,
    nm_criado_por               VARCHAR2(50 CHAR),
    nm_alterado_por             VARCHAR2(50 CHAR)
);

ALTER TABLE t_spa_usuario ADD CONSTRAINT t_spa_usuario_pk PRIMARY KEY ( cd_usuario );

ALTER TABLE t_spa_usuario ADD CONSTRAINT index_1v1 UNIQUE ( nm_usuario );

CREATE TABLE t_spa_usuario_permissao (
    cd_usuario      NUMBER NOT NULL,
    cd_permissao    NUMBER NOT NULL,
    dt_criacao      TIMESTAMP DEFAULT current_timestamp,
    dt_alteracao    TIMESTAMP,
    nm_criado_por   VARCHAR2(50 CHAR),
    nm_alterado_por VARCHAR2(50 CHAR)
);

ALTER TABLE t_spa_usuario_permissao ADD CONSTRAINT pk_usuario_permissao PRIMARY KEY ( cd_usuario,
                                                                                      cd_permissao );

ALTER TABLE t_spa_usuario_permissao
    ADD CONSTRAINT fk_permissao FOREIGN KEY ( cd_permissao )
        REFERENCES t_spa_permissao ( cd_permissao );

ALTER TABLE t_spa_usuario_permissao
    ADD CONSTRAINT fk_usuario FOREIGN KEY ( cd_usuario )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_cultura
    ADD CONSTRAINT t_spa_cultura_t_usuario_alterado_fk FOREIGN KEY ( cd_alterado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_cultura
    ADD CONSTRAINT t_spa_cultura_t_usuario_criado_fk FOREIGN KEY ( cd_criado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_estado
    ADD CONSTRAINT t_spa_estado_t_usuario_alterado_fk FOREIGN KEY ( cd_alterado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_estado
    ADD CONSTRAINT t_spa_estado_t_usuario_criado_fk FOREIGN KEY ( cd_criado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_producao
    ADD CONSTRAINT t_spa_producao_t_cultura_fk FOREIGN KEY ( cd_cultura )
        REFERENCES t_spa_cultura ( cd_cultura );

ALTER TABLE t_spa_producao
    ADD CONSTRAINT t_spa_producao_t_estado_fk FOREIGN KEY ( cd_estado )
        REFERENCES t_spa_estado ( cd_estado );

ALTER TABLE t_spa_producao
    ADD CONSTRAINT t_spa_producao_t_usuario_alterado_fk FOREIGN KEY ( cd_alterado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_producao
    ADD CONSTRAINT t_spa_producao_t_usuario_criado_fk FOREIGN KEY ( cd_criado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

ALTER TABLE t_spa_produtores
    ADD CONSTRAINT t_spa_produtores_t_cultura_fk FOREIGN KEY ( cd_cultura )
        REFERENCES t_spa_cultura ( cd_cultura );

ALTER TABLE t_spa_produtores
    ADD CONSTRAINT t_spa_produtores_t_estado_fk FOREIGN KEY ( cd_estado )
        REFERENCES t_spa_estado ( cd_estado );

ALTER TABLE t_spa_produtores
    ADD CONSTRAINT t_spa_produtores_t_usuario_criado_fk FOREIGN KEY ( cd_criado_por )
        REFERENCES t_spa_usuario ( cd_usuario );

CREATE SEQUENCE t_spa_cultura_cd_cultura_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_spa_cultura_cd_cultura_trg BEFORE
    INSERT ON t_spa_cultura
    FOR EACH ROW
    WHEN ( new.cd_cultura IS NULL )
BEGIN
    :new.cd_cultura := t_spa_cultura_cd_cultura_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_estado_cd_estado_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_spa_estado_cd_estado_trg BEFORE
    INSERT ON t_spa_estado
    FOR EACH ROW
    WHEN ( new.cd_estado IS NULL )
BEGIN
    :new.cd_estado := t_spa_estado_cd_estado_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_permissao_cd_permissao_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER t_spa_permissao_cd_permissao_trg BEFORE
    INSERT ON t_spa_permissao
    FOR EACH ROW
    WHEN ( new.cd_permissao IS NULL )
BEGIN
    :new.cd_permissao := t_spa_permissao_cd_permissao_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_producao_cd_producao_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_spa_producao_cd_producao_trg BEFORE
    INSERT ON t_spa_producao
    FOR EACH ROW
    WHEN ( new.cd_producao IS NULL )
BEGIN
    :new.cd_producao := t_spa_producao_cd_producao_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_produtores_cd_produtores_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_spa_produtores_cd_produtores_trg BEFORE
    INSERT ON t_spa_produtores
    FOR EACH ROW
    WHEN ( new.cd_produtores IS NULL )
BEGIN
    :new.cd_produtores := t_spa_produtores_cd_produtores_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_usuario_cd_usuario_seq START WITH 1 NOCACHE;

CREATE OR REPLACE TRIGGER t_spa_usuario_cd_usuario_trg BEFORE
    INSERT ON t_spa_usuario
    FOR EACH ROW
    WHEN ( new.cd_usuario IS NULL )
BEGIN
    :new.cd_usuario := t_spa_usuario_cd_usuario_seq.nextval;
END;
/

CREATE SEQUENCE t_spa_usuario_permissao_cd_usuario_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_spa_usuario_permissao_cd_usuario_trg BEFORE
    INSERT ON t_spa_usuario_permissao
    FOR EACH ROW
    WHEN ( new.cd_usuario IS NULL )
BEGIN
    :new.cd_usuario := t_spa_usuario_permissao_cd_usuario_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
